name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app

      # - name: Run tests
      #   run: xcodebuild clean test -project "MTMR.xcodeproj" -scheme "UnitTests"

      - name: Build Archive
        run: xcodebuild archive -project "MTMR.xcodeproj" -scheme "MTMR" -archivePath Release/App.xcarchive

      - name: Build App
        run: xcodebuild -project "MTMR.xcodeproj" -exportArchive -archivePath Release/App.xcarchive -exportOptionsPlist export-options.plist -exportPath Release
