name: Swift

on: [push]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install create-dmg
        run: npm i -g create-dmg

      # - name: Build Archive
      #   run: xcodebuild archive -project "MTMR.xcodeproj" -scheme "MTMR" -archivePath Release/App.xcarchive | xcpretty

      # - name: Build App
      #   run: xcodebuild -project "MTMR.xcodeproj" -exportArchive -archivePath Release/App.xcarchive -exportOptionsPlist export-options.plist -exportPath Release | xcpretty


